# Generated by Django 6.0.3 on 2026-05-23 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_inclusao',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Data usada para ordenar a lista de leitura', verbose_name='Data de Inclusão'),
        ),
    ]
