# Generated by Django 6.0.3 on 2026-04-15 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0008_tipopeca_peca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome da Matéria')),
                ('efeito', models.CharField(choices=[('IMPEDE', 'Impede a confecção do MPPF'), ('IN40', 'Demanda aplicação da IN40'), ('NEUTRO', 'Apenas Informativo / Alerta na tela')], default='NEUTRO', max_length=10, verbose_name='Efeito na Triagem')),
                ('ativa', models.BooleanField(default=True, verbose_name='Regra Ativa?')),
            ],
            options={
                'verbose_name': 'Matéria de Triagem',
                'verbose_name_plural': 'Matérias de Triagem',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ExpressaoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('texto', models.CharField(max_length=600, verbose_name='Expressão / Fragmento de Texto')),
                ('data_referencia', models.DateField(blank=True, null=True, verbose_name='Data de Referência')),
                ('usar_regex', models.BooleanField(default=False, verbose_name='É Expressão Regular (Regex)?')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressoes', to='mppf.materia')),
            ],
            options={
                'verbose_name': 'Expressão de Matéria',
                'verbose_name_plural': 'Expressões de Matérias',
            },
        ),
        migrations.CreateModel(
            name='TriagemMPPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('texto_despacho_admissibilidade', models.TextField(blank=True, null=True, verbose_name='Texto do DA para Conferência')),
                ('quantidade_de_recursos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Recursos')),
                ('foi_triado', models.BooleanField(default=False, verbose_name='Foi Triado?')),
                ('foi_editada_DA', models.BooleanField(default=False, verbose_name='Foi Editada DA?')),
                ('foi_conferida_a_quantidade_de_recursos', models.BooleanField(default=False, verbose_name='Foi Conferida Qtd. de Recursos?')),
                ('fazer_mppf', models.BooleanField(default=True, verbose_name='Fazer MPPF?')),
                ('fazer_mppf_com_in40', models.BooleanField(default=False, verbose_name='Fazer MPPF com IN40?')),
                ('foi_lancado_GE', models.BooleanField(default=False, verbose_name='Foi Lançado no GE?')),
                ('materias_identificadas', models.ManyToManyField(blank=True, help_text='Matérias encontradas automaticamente no texto do DA.', related_name='triagens_onde_aparece', to='mppf.materia')),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triagem_mppf', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Triagem MPPF',
                'verbose_name_plural': 'Triagens MPPF',
            },
        ),
    ]
