# Generated by Django 6.0.3 on 2026-04-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triagemmppf',
            options={'ordering': ['quantidade_de_recursos', 'paginas'], 'verbose_name': 'Triagem MPPF', 'verbose_name_plural': 'Triagens MPPF'},
        ),
        migrations.RemoveField(
            model_name='triagemmppf',
            name='materias_identificadas',
        ),
        migrations.AddField(
            model_name='triagemmppf',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='triagens_onde_aparece', to='mppf.materia'),
        ),
        migrations.AddField(
            model_name='triagemmppf',
            name='paginas',
            field=models.FloatField(default=0, verbose_name='Páginas Estimadas'),
        ),
        migrations.AlterField(
            model_name='triagemmppf',
            name='texto_despacho_admissibilidade',
            field=models.TextField(blank=True, null=True, verbose_name='Texto da DA'),
        ),
    ]
