# Generated by Django 6.0.3 on 2026-04-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0002_alter_triagemmppf_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagemmppf',
            name='fazer_mppf',
            field=models.BooleanField(default=False, verbose_name='Fazer MPPF?'),
        ),
    ]
