# Generated by Django 6.0.3 on 2026-04-16 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0003_alter_triagemmppf_fazer_mppf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressaomateria',
            name='data_referencia',
        ),
        migrations.AddField(
            model_name='materia',
            name='data_referencia',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1), null=True, verbose_name='Data de Referência'),
        ),
    ]
