# Generated by Django 6.0.3 on 2026-04-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0004_remove_expressaomateria_data_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagemmppf',
            name='fazer_mppf_com_in40',
        ),
        migrations.AddField(
            model_name='triagemmppf',
            name='fazer_mppf_in40',
            field=models.BooleanField(default=False, verbose_name='Fazer MPPF IN40?'),
        ),
        migrations.AddField(
            model_name='triagemmppf',
            name='fazer_mppf_misto',
            field=models.BooleanField(default=False, verbose_name='Fazer MPPF misto?'),
        ),
    ]
