# Generated by Django 6.0.3 on 2026-04-17 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0005_remove_triagemmppf_fazer_mppf_com_in40_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoTriagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Resultado')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Identificador (Slug)')),
                ('cor_classe', models.CharField(default='primary', max_length=50, verbose_name='Classe CSS/Cor')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resultado de Triagem',
                'verbose_name_plural': 'Resultados de Triagem',
            },
        ),
        migrations.RemoveField(
            model_name='triagemmppf',
            name='fazer_mppf',
        ),
        migrations.RemoveField(
            model_name='triagemmppf',
            name='fazer_mppf_in40',
        ),
        migrations.RemoveField(
            model_name='triagemmppf',
            name='fazer_mppf_misto',
        ),
        migrations.RemoveField(
            model_name='triagemmppf',
            name='foi_triado',
        ),
        migrations.AddField(
            model_name='triagemmppf',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_triagem', to='mppf.resultadotriagem'),
        ),
    ]
