# Generated by Django 6.0.3 on 2026-04-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0006_resultadotriagem_remove_triagemmppf_fazer_mppf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadotriagem',
            name='ordem',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordem'),
        ),
    ]
