# Generated by Django 6.0.3 on 2026-04-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0007_resultadotriagem_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultadotriagem',
            options={'ordering': ['ordem'], 'verbose_name': 'Resultado de Triagem', 'verbose_name_plural': 'Resultados de Triagem'},
        ),
        migrations.AddField(
            model_name='materia',
            name='nivel_prioridade',
            field=models.IntegerField(default=1),
        ),
    ]
