# Generated by Django 6.0.3 on 2026-04-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0008_alter_resultadotriagem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='nivel_prioridade',
        ),
        migrations.AddField(
            model_name='resultadotriagem',
            name='nivel_prioridade',
            field=models.IntegerField(default=1),
        ),
    ]
