# Generated by Django 6.0.3 on 2026-04-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0009_remove_materia_nivel_prioridade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='efeito',
        ),
        migrations.AddField(
            model_name='materia',
            name='solucoes_compativeis',
            field=models.ManyToManyField(blank=True, help_text='Quais soluções ficam habilitadas quando essa matéria aparece?', to='mppf.resultadotriagem'),
        ),
    ]
