# Generated by Django 6.0.3 on 2026-04-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0010_remove_materia_efeito_materia_solucoes_compativeis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='solucoes_compativeis',
            field=models.ManyToManyField(blank=True, help_text='Quais soluções ficam habilitadas quando essa matéria aparece?', related_name='materias_que_permitem', to='mppf.resultadotriagem'),
        ),
    ]
