# Generated by Django 6.0.3 on 2026-04-17 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0011_alter_materia_solucoes_compativeis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagemmppf',
            name='materias',
        ),
        migrations.CreateModel(
            name='TriagemMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('origem', models.CharField(choices=[('SISTEMA', 'Identificado pelo Robô'), ('HUMANO', 'Adicionado Manualmente')], default='HUMANO', max_length=10)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mppf.materia')),
                ('triagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mppf.triagemmppf')),
            ],
            options={
                'unique_together': {('triagem', 'materia')},
            },
        ),
    ]
