# Generated by Django 6.0.3 on 2026-04-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0012_remove_triagemmppf_materias_triagemmateria'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagemmppf',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='triagens_onde_aparece', through='mppf.TriagemMateria', to='mppf.materia'),
        ),
    ]
