# Generated by Django 6.0.3 on 2026-04-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0013_triagemmppf_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='descrição',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Matéria'),
        ),
    ]
