# Generated by Django 6.0.3 on 2026-04-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0014_materia_descrição'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
