# Generated by Django 6.0.3 on 2026-04-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0015_rename_descrição_materia_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expressaomateria',
            options={'ordering': ['texto'], 'verbose_name': 'Expressão de Matéria', 'verbose_name_plural': 'Expressões de Matérias'},
        ),
        migrations.RemoveField(
            model_name='triagemmppf',
            name='foi_lancado_GE',
        ),
        migrations.AddField(
            model_name='triagemmppf',
            name='foi_criada_minuta_GE',
            field=models.BooleanField(default=False, verbose_name='Foi criada minuta no GE?'),
        ),
        migrations.AddField(
            model_name='triagemmppf',
            name='foi_lancada_DA_no_GE',
            field=models.BooleanField(default=False, verbose_name='Foi lançada DA no GE?'),
        ),
    ]
