# Generated by Django 6.0.3 on 2026-04-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0016_alter_expressaomateria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagemmppf',
            name='foi_enviado_para_assinatura',
            field=models.BooleanField(default=False, verbose_name='Foi lançada DA no GE?'),
        ),
    ]
