# Generated by Django 6.0.3 on 2026-04-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mppf', '0017_triagemmppf_foi_enviado_para_assinatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressaoMarcador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('texto', models.CharField(max_length=600, verbose_name='Expressão / Fragmento de Texto')),
            ],
            options={
                'verbose_name': 'Marcador',
                'verbose_name_plural': 'Marcadores',
                'ordering': ['texto'],
            },
        ),
        migrations.AlterField(
            model_name='triagemmppf',
            name='foi_enviado_para_assinatura',
            field=models.BooleanField(default=False, verbose_name='Foi enviado para assinatura?'),
        ),
    ]
