# Generated by Django 6.0.3 on 2026-03-28 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrgaoJulgador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoMinuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMinuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_completa', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=25)),
                ('data_entrada', models.DateField()),
                ('movimentacoes', models.TextField(blank=True, null=True)),
                ('admissibilidade', models.TextField(blank=True, null=True)),
                ('andamento', models.CharField(blank=True, max_length=255, null=True)),
                ('observacao_full', models.TextField(blank=True, null=True, verbose_name='Conteúdo da Observação')),
                ('observacao_responsavel_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável pela Obs')),
                ('advogados', models.ManyToManyField(blank=True, to='processos.advogado')),
                ('assuntos', models.ManyToManyField(blank=True, to='processos.assunto')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.classe')),
                ('movimentacao_interna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.movimentacaointerna')),
                ('orgao_julgador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.orgaojulgador')),
                ('partes_autoras', models.ManyToManyField(blank=True, related_name='processos_autor', to='processos.parte')),
                ('partes_res', models.ManyToManyField(blank=True, related_name='processos_reu', to='processos.parte')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meus_processos', to=settings.AUTH_USER_MODEL)),
                ('situacao_minuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.situacaominuta')),
                ('tipo_minuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.tipominuta')),
            ],
            options={
                'unique_together': {('numero', 'data_entrada')},
            },
        ),
    ]
