# Generated by Django 6.0.3 on 2026-03-28 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='observacao_full',
            new_name='obs',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='observacao_responsavel_nome',
        ),
        migrations.AddField(
            model_name='processo',
            name='obs_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
