# Generated by Django 6.0.3 on 2026-03-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_advogado_atualizado_em_advogado_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advogado',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='assunto',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='movimentacaointerna',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='orgaojulgador',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='parte',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='situacaominuta',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='tipominuta',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='responsavel',
            name='inicial',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
