# Generated by Django 6.0.3 on 2026-04-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_alter_advogado_options_alter_assunto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsavel',
            options={'ordering': ['nome_completo']},
        ),
        migrations.AddField(
            model_name='processo',
            name='esta_no_acervo',
            field=models.BooleanField(default=False),
        ),
    ]
