# Generated by Django 6.0.3 on 2026-04-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0006_alter_responsavel_options_processo_esta_no_acervo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': [models.OrderBy(models.F('data_entrada'), descending=True, nulls_first=True)]},
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_entrada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
