# Generated by Django 6.0.3 on 2026-04-14 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0007_alter_processo_options_alter_processo_data_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cod_peca', models.BigIntegerField(unique=True)),
                ('data_publicacao', models.DateTimeField()),
                ('formato_original', models.CharField(max_length=100)),
                ('download_url', models.URLField(max_length=1000)),
                ('conteudo_texto', models.TextField(blank=True, null=True, verbose_name='Conteúdo da Peça (Texto)')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='processos.processo')),
                ('tipo_peca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.tipopeca')),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
