# Generated by Django 6.0.3 on 2026-05-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0008_tipopeca_peca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=500, unique=True)),
                ('sigla', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
