# Generated by Django 6.0.3 on 2026-05-02 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0009_ministro'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='relator',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relator_em', to='processos.ministro'),
        ),
    ]
