# Generated by Django 6.0.3 on 2026-05-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0010_processo_relator'),
    ]

    operations = [
        migrations.AddField(
            model_name='advogado',
            name='gera_impedimento',
            field=models.BooleanField(default=False, verbose_name='Gera Impedimento?'),
        ),
        migrations.AddField(
            model_name='processo',
            name='impedido',
            field=models.BooleanField(default=False, verbose_name='Impedido?'),
        ),
    ]
