# Generated by Django 6.0.3 on 2026-03-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(help_text='Ex: Pauta 13 a 22.04.2026 Virtual', max_length=200)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
