# Generated by Django 6.0.3 on 2026-03-30 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0001_initial'),
        ('processos', '0004_advogado_atualizado_em_advogado_criado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusRevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(help_text='Ex: Pendente, Corrigido erro material, Liberada', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Explicação opcional sobre quando usar este status')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para ocultar este status das novas revisões')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListaProcessos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(help_text='Ex: Lote Inicial (10/04), Lote Complementar (15/04)', max_length=100)),
                ('data_inclusao', models.DateField()),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='pautas.pauta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevisaoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('anotacoes', models.TextField(blank=True, help_text='As suas notas sobre o processo nesta pauta.')),
                ('inclusao_tardia', models.BooleanField(default=False)),
                ('lista_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processos_revisar', to='pautas.listaprocessos')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='pautas.pauta')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='revisoes_pauta', to='processos.processo')),
                ('status', models.ManyToManyField(blank=True, related_name='revisoes', to='pautas.statusrevisao')),
            ],
        ),
        migrations.CreateModel(
            name='ObservacaoRevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tema', models.TextField(help_text='Tema ou contexto principal da observação.')),
                ('observacao', models.TextField(help_text='Conteúdo detalhado da observação.')),
                ('duvida', models.BooleanField(default=False, help_text='Marque se isto for uma dúvida pendente.')),
                ('revisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='pautas.revisaoprocesso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='revisaoprocesso',
            constraint=models.UniqueConstraint(fields=('pauta', 'processo'), name='unique_processo_por_pauta'),
        ),
    ]
