# Generated by Django 6.0.3 on 2026-04-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0002_statusrevisao_listaprocessos_revisaoprocesso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisaoprocesso',
            name='inclusao_tardia',
        ),
    ]
