# Generated by Django 6.0.3 on 2026-04-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0003_remove_revisaoprocesso_inclusao_tardia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaprocessos',
            name='data_inclusao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
