# Generated by Django 6.0.3 on 2026-04-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0004_alter_listaprocessos_data_inclusao'),
        ('processos', '0007_alter_processo_options_alter_processo_data_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisaoprocesso',
            name='minutante',
            field=models.ManyToManyField(blank=True, null=True, related_name='revisoes', to='processos.responsavel'),
        ),
    ]
