# Generated by Django 6.0.3 on 2026-04-02 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0005_revisaoprocesso_minutante'),
        ('processos', '0007_alter_processo_options_alter_processo_data_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisaoprocesso',
            name='minutante',
        ),
        migrations.AddField(
            model_name='revisaoprocesso',
            name='minutante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes_minutadas', to='processos.responsavel'),
        ),
    ]
