# Generated by Django 6.0.3 on 2026-04-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0006_remove_revisaoprocesso_minutante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='pasta',
            field=models.CharField(blank=True, help_text='Caminho da pasta com as minutas .docx', max_length=500, null=True),
        ),
    ]
