# Generated by Django 6.0.3 on 2026-04-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0007_pauta_pasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisaoprocesso',
            name='pulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revisaoprocesso',
            name='rr_provido',
            field=models.BooleanField(default=False),
        ),
    ]
