# Generated by Django 6.0.3 on 2026-04-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0008_revisaoprocesso_pulado_revisaoprocesso_rr_provido'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusrevisao',
            name='eh_revisado',
            field=models.BooleanField(default=False),
        ),
    ]
