# Generated by Django 6.0.3 on 2026-04-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0009_statusrevisao_eh_revisado'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisaoprocesso',
            name='tempo_gasto',
            field=models.IntegerField(default=0, help_text='Tempo total gasto na revisão (em segundos)'),
        ),
    ]
