# Generated by Django 6.0.3 on 2026-05-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0010_revisaoprocesso_tempo_gasto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pauta',
            options={'ordering': ['data_inicio']},
        ),
    ]
