# Generated by Django 6.0.3 on 2026-05-03 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0011_alter_pauta_options'),
        ('processos', '0010_processo_relator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('resumo_memorial', models.TextField(blank=True)),
                ('resumo_proposta_decisao', models.TextField(blank=True, help_text='Resumo da proposta de decisão que consta do plenário')),
                ('link_memorial', models.URLField(blank=True, help_text='Link para o memorial no Google Drive', max_length=500, null=True)),
                ('partes', models.ManyToManyField(blank=True, related_name='memoriais', to='processos.parte')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauta_memoriais', to='pautas.pauta')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo_memoriais', to='processos.processo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AtendimentoAdvogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_horario', models.DateTimeField(help_text='Data e horário do atendimento')),
                ('resumo_observacoes', models.TextField(blank=True, help_text='Resumo das observações do advogado')),
                ('resumo_proposta_decisao', models.TextField(blank=True, help_text='Resumo da proposta de decisão que consta do plenário')),
                ('link_audio', models.URLField(blank=True, help_text='Link para o audio', max_length=500, null=True)),
                ('advogados', models.ManyToManyField(blank=True, related_name='advogado_memoriais', to='processos.advogado')),
                ('partes', models.ManyToManyField(blank=True, related_name='parte_memoriais', to='processos.parte')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauta_atendimentos', to='pautas.pauta')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo_atendimentos', to='processos.processo')),
                ('memorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_vinculados', to='pautas.memorial')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
